### ISSUE TITLE
Does no work with "Share by a email link"

### ISSUE THREAD

**Issue by flaviove** [juliushaertl/direct_menu#40] opened 2016-09-14 16:20 UTC
After activate Direct Menu 0.9.2 3 on ownCloud 9.1, the option share a file by a email link stops to work.

**Comment by juliusknorr** [comment] 2016-09-15 09:08
I don't see any Share file by email link in owncloud 9.1 even without direct_menu. Can you verify that is works without direct_menu being enabled?

**Comment by flaviove** [comment] 2016-09-15 12:19
Hi Julius.

I had a big help from RealRancor posted here
https://central.owncloud.org/t/share-files-using-email-link-does-not-work-link-show-up-white-page/2401/1
in order to find out what was going on when I try to share a file to
someone (see the attached file) that is not a ownCloud user. If I had a
"Direct Menu 0.9.2" enable the email showed up but the link goes to a blank
page instead a link to download a shared file.
Any thing else please drop a line.
Best regards.
Flávio Veras

2016-09-15 6:08 GMT-03:00 Julius Härtl notifications@github.com:

**Comment by juliusknorr** [comment] 2016-09-18 15:00
@flaviove I cannot reproduce this issue on my local testing installation, can you check if there are any error messages inside your browser log?

**Comment by flaviove** [comment] 2016-09-19 11:29
I didn´t get any from fierefox. Even using this
For 64-bit Windows:

cd c:\
set MOZ_LOG_MODULES=timestamp,rotate:200,nsHttp:5,nsSocketTransport:5,nsStreamPump:5,nsHostResolver:5
set MOZ_LOG_FILE=%TEMP%\log.txt
cd "Program Files (x86)\Mozilla Firefox"
.\firefox.exe

Please show me the rocks way if I can do something diferent to help.

**Comment by juliusknorr** [comment] 2016-10-18 15:41
@flaviove just hit F12, go to the console tab and reload the page.

**Comment by juliusknorr** [comment] 2017-01-10 14:22
I'll close this since I cannot reproduce. Feel free to reopen when you have the error messages.

**Closed as completed by juliusknorr** 2017-01-10 14:22 UTC
Labels: info-needed
