### ISSUE TITLE
 icon size too big in internet explorer

### ISSUE THREAD

**Issue by hele333** [juliushaertl/direct_menu#7] opened 2015-07-01 12:09 UTC
works perfekt in firefox and opera, but using the IE 11, the icons don't fit in the bar, they are too big, and not all can be seen.

The hover does also not work.

![direct menue ie error](https://cloud.githubusercontent.com/assets/13134733/8454064/b5a92b42-1ffa-11e5-8edd-631efaf60fa2.jpg)

**Comment by TheAgentK** [comment] 2015-07-08 10:03
The IE has some Problemes with scaling the SVG Icons to the right size.

I made a workaround for this.
https://github.com/TheAgentK/direct_menu

I change the SVG Files in the IW with the png files in the IE.

**Comment by mdusher** [comment] 2015-07-21 03:09
I've just tested this out and I believe it's because the SVG files do not have a viewBox property. From what I can gather IE requires the viewBox property in the SVG file for the image to scale properly.

**Comment by juliusknorr** [comment] 2015-10-08 10:46
As the pull request by @TheAgentK is merged now, this issue should be fixed. Can somebody prove, because I don't have an IE around at the moment.

**Comment by juliusknorr** [comment] 2015-10-19 10:33
Seems to work in IE11 and the fix was also confirmed here: https://apps.owncloud.com/content/show.php?content=169148#c479653

**Closed as completed by juliusknorr** 2015-10-19 10:33 UTC
